# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StarterKit' do 


    
#pod 'react-native-image-crop-picker', :path => '../node_modules/react-native-image-crop-picker/ios'
pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'RCTText'
] 
  target 'StarterKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
